# Generated by Django 5.0 on 2026-01-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="embedding_status",
            field=models.CharField(default="embedded", max_length=20),
        ),
    ]
