# Generated by Django 5.0 on 2026-01-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_auto_20260107_1520"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="processed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="processed_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
