# Generated by Django 5.0 on 2026-01-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0012_alter_message_from_user_alter_thread_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thread",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="thread",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
