# Generated by Django 5.0 on 2026-01-16 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0014_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
    ]
