# Generated by Django 5.0 on 2026-01-05 06:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_document_embedding_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="embedding_status",
        ),
    ]
