# Generated by Django 5.0 on 2026-01-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_remove_document_embedding_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
