# Generated by Django 5.0 on 2026-01-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_document_processed_document_processed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="thread",
            name="title",
            field=models.CharField(default="New Chat", max_length=200),
        ),
    ]
