# Generated by Django 5.0 on 2026-01-07 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_alter_document_title_alter_thread_title"),
    ]

    operations = []
