# Generated by Django 5.0 on 2026-01-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_alter_document_processed_alter_document_processed_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="thread",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="thread",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
