# Generated by Django 5.0 on 2026-01-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_alter_document_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.AlterModelOptions(
            name="thread",
            options={},
        ),
        migrations.RemoveField(
            model_name="document",
            name="processed",
        ),
        migrations.RemoveField(
            model_name="document",
            name="processed_at",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="thread",
            name="title",
            field=models.CharField(default="New chat", max_length=100),
        ),
    ]
