# Generated by Django 5.0 on 2026-01-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_alter_document_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="from_user",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="thread",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
