# Generated by Django 5.0 on 2026-01-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0011_alter_message_from_user_alter_thread_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="from_user",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="thread",
            name="title",
            field=models.CharField(default="New chat", max_length=100),
        ),
    ]
