# Generated by Django 5.0 on 2026-01-16 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0013_alter_thread_options_thread_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created_at"]},
        ),
        migrations.RenameField(
            model_name="document",
            old_name="uploaded_at",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="from_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="thread",
            name="title",
            field=models.CharField(default="New Chat", max_length=200),
        ),
        migrations.AlterField(
            model_name="thread",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
